language: rust

dist: trusty

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

branches:
  except:
    - legacy

script:
  - cd bgmrank-cli
  - cargo build --verbose
  - cd ../libbgmrank
  - cargo build --verbose
  - cargo test --verbose
