[package]
name = "libbgmrank"
version = "0.0.1"
authors = ["Xidorn Quan <me@upsuper.org>"]
description = "Personal rank statistics for Bangumi"
repository = "https://github.com/upsuper/bgmrank"
license = "MIT"
keywords = ["bangumi"]

[lib]
name = "libbgmrank"
path = "lib.rs"

[dependencies]
enum-set = "0.0.6"
selectors = "0.14"
html5ever = "0.9"
html5ever-atoms = "0.1.3"
kuchiki = "0.4.1"
hyper = "0.10.4"
hyper-rustls = "0.3.3"

[dev-dependencies]
float-cmp = "0.2.3"
